server:
  port: 8084
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes[0]:
        id: QUIZ-SERVICE
        uri: lb://QUIZ-SERVICE
        predicates[0]: Path= /quiz/**
      routes[1]:
        id: QUESTION-SERVICE
        uri: lb://QUESTION-SERVICE
        predicates[0]: Path= /question/**

