server:
  port: 8081
spring:
  application:
    name: QUIZ-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/Quiz
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/